name: "Build Signed APK"
description: "Build a signed APK of your Android application"

inputs:

  keystore:
    description: "Keystore file encoded as base64"
    required: true
    
  keystore_password:
    description: "Keystore file password"
    required: true
    
  key_alias:
    description: "Key alias"
    required: true
    
  key_password:
    description: "Key password"
    required: true
    
runs:
  using: "composite"
  steps:

    - uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8

    - run: echo "${{ inputs.keystore }}" | base64 -d > signing-key.jks

    - run: chmod +x ./gradlew

    - run: ./gradlew build

    - run: ./gradlew assembleRelease
        -Pandroid.injected.signing.store.file=./signing-key.jks 
        -Pandroid.injected.signing.store.password=${{ inputs.keystore_password }} 
        -Pandroid.injected.signing.key.alias=${{ inputs.key_alias }} 
        -Pandroid.injected.signing.key.password=${{ inputs.key_password }}
