name: "Build Signed APK"
description: "Build a signed APK of your Android application"

branding:
  icon: cpu
  color: red

inputs:

  keystore:
    description: "Keystore file encoded as base64"
    required: true
    
  keystore_password:
    description: "Keystore file password"
    required: true
    
  key_alias:
    description: "Key alias"
    required: true
    
  key_password:
    description: "Key password"
    required: true
    
runs:
  using: "composite"
  steps:

    - run: |
      sudo apt-get -y install default-jre
      echo "${{ inputs.keystore }}" | base64 -d > $GITHUB_WORKSPACE/signing-key.jks
      chmod +x ./gradlew
      ./gradlew build
      ./gradlew assembleRelease \
        -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/signing-key.jks \
        -Pandroid.injected.signing.store.password=${{ inputs.keystore_password }} \
        -Pandroid.injected.signing.key.alias=${{ inputs.key_alias }} \
        -Pandroid.injected.signing.key.password=${{ inputs.key_password }}
      rm $GITHUB_WORKSPACE/signing-key.jks
    shell: bash
